name: Build, Test & Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-test-generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen

      - name: Installing dependencies...
        run: dotnet restore

      - name: Building...
        run: dotnet build

      - name: Running test...
        run: dotnet test

      - name: Generating docs...
        working-directory: docs
        run: doxygen Doxyfile
        continue-on-error: false

      - name: Commit and push generated docs
        working-directory: docs
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-pages
          git pull
          git add .
          git commit -m "Update Doxygen docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages

