name: Build, Test & Generate Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-test-generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen

      - name: Installing dependencies...
        run: dotnet restore

      - name: Building...
        run: dotnet build

      - name: Running test...
        run: dotnet test

      - name: Generating docs...
        working-directory: docs
        run: doxygen Doxyfile
        continue-on-error: false

      - name: Commit and push generated docs
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Guardar los HTML generados temporalmente
          mkdir -p /tmp/docs
          cp -r docs/html/* /tmp/docs/

          # Cambiar a la ra√≠z del repo
          cd $GITHUB_WORKSPACE

          # Cambiar a la rama gh-pages (o crearla si no existe)
          git fetch origin gh-pages || true
          git switch -c gh-pages origin/gh-pages || git checkout --orphan gh-pages

          # Limpiar todo y copiar los nuevos docs
          rm -rf ./*
          cp -r /tmp/docs/* .

          # Commit y push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Doxygen docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages

